### ISSUE TITLE
Please create area and Dockerfile for this service in CMSKubernetes repository

### ISSUE THREAD

**Issue by muhammadimranfarooqi** [vkuznet/CMSAMQProxy#1]
Hi Valentin,

I noticed relevant dockerfile and directory for this service does not exist in the CMSKubernetes repository and latest images for this service have been deleted using the cleanup utility of the registry. Need to create new image and relevant dockerifle is needed in the repository.

**Comment by vkuznet** [comment]
You may create new area in CMSKubernetes/docker and use the [Dockerfile](https://github.com/vkuznet/CMSAMQProxy/blob/main/Dockerfile) from this repo

**Comment by muhammadimranfarooqi** [comment]
Thanks @vkuznet . 

Its done https://github.com/dmwm/CMSKubernetes/pull/1147
